name: Feature Request
description: Suggest a new feature
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: What would you like to see?
    validations:
      required: true
